# Generated by Django 4.2.5 on 2023-10-25 03:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='briberyreductiondata',
            name='district',
        ),
        migrations.AddField(
            model_name='briberyreductiondata',
            name='services',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
