# Generated by Django 4.2.5 on 2023-10-25 11:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        ('indicators', '0002_remove_briberyreductiondata_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatordata',
            name='answer_choice_comm_stability',
            field=models.CharField(blank=True, choices=[('', 'Select an answer'), ('Very much', 'Very much'), ('Somewhat', 'Somewhat'), ('A little bit', 'A little bit'), ('Not at all', 'Not at all')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='indicatordata',
            name='answer_choice_trust',
            field=models.CharField(blank=True, choices=[('', 'Select an answer'), ('A lot', 'A lot'), ('Somewhat', 'Somewhat'), ('Just a little', 'Just a little'), ('Not at all', 'Not at all')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='indicatordata',
            name='bribery_services',
            field=models.CharField(blank=True, choices=[('', 'Select a service'), ('Medical services', 'Medical services'), ('Public school', 'Public school'), ('Identity documents', 'Identity documents')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='indicatordata',
            name='media_outlets',
            field=models.CharField(blank=True, choices=[('', 'Select a media outlet'), ('Notice Board', 'Notice Board'), ('Radio', 'Radio'), ('Local online news outlet', 'Local online news outlet'), ('Print Newspaper', 'Print Newspaper'), ('WhatsApp', 'WhatsApp'), ('Other Social Media', 'Other Social Media'), ('Other', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='indicatordata',
            name='date_submitted',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='indicatordata',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.district'),
        ),
    ]
